services:
  webapp:
    image: "node:16.17.1"
    command: 
      - /bin/bash
      - -c 
      - | 
        curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
        cp package.json pnpm-lock.yaml ./
        pnpm install --frozen-lockfile
        pnpm run build
  webservice:
    image: "nginx:latest"
    ports:
      - "8080:8080"
    expose:
      - 8080
    command: 
      - /bin/bash
      - -c 
      - |
        cp ./dist/ /usr/share/nginx/html/
        cp ./nginx.conf /etc/nginx/conf.d/