name: "Vue3 Todo App Build"
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2.6.0
        with: 
          persist-credentials: false
      - name: Install and Build
        run: |
          npm install
          npm run build
          pwd
          ls -al